const animalsAndBirds = [
    'Lion',
    'Elephant',
    'Tiger',
    'Giraffe',
    'Zebra',
    'Bear',
    'Kangaroo',
    'Panda',
    'Wolf',
    'Deer',
    'Rabbit',
    'Fox',
    'Hippopotamus',
    'Rhinoceros',
    'Monkey',
    'Dolphin',
    'Whale',
    'Shark',
    'Crocodile',
    'Turtle',
    'Eagle',
    'Parrot',
    'Sparrow',
    'Peacock',
    'Owl',
    'Penguin',
    'Flamingo',
    'Pigeon',
    'Swan',
    'Seagull',
    'Woodpecker',
    'Hummingbird',
    'Kingfisher',
    'Robin',
    'Canary',
    'Hawk',
    'Ostrich',
    'Pelican',
    'Toucan',
    'Vulture',
  ];
  
  const adjectives = [
    'Brave',
    'Majestic',
    'Ferocious',
    'Tall',
    'Striped',
    'Strong',
    'Agile',
    'Cuddly',
    'Fierce',
    'Graceful',
    'Quick',
    'Sly',
    'Massive',
    'Horned',
    'Curious',
    'Intelligent',
    'Gentle',
    'Powerful',
    'Stealthy',
    'Shelled',
    'Regal',
    'Colorful',
    'Chirpy',
    'Elegant',
    'Nocturnal',
    'Aquatic',
    'Pink',
    'Urban',
    'Serene',
    'Coastal',
    'Persistent',
    'Tiny',
    'Vibrant',
    'Cheerful',
    'Sunny',
    'Sharp-eyed',
    'Flightless',
    'Wide-beaked',
    'Exotic',
    'Scavenging',
  ];

const getRandomName = () => {
    const randomAdjective =
      adjectives[Math.floor(Math.random() * adjectives.length)];
    const randomAnimalOrBird =
      animalsAndBirds[Math.floor(Math.random() * animalsAndBirds.length)];
    const randomName = randomAdjective + randomAnimalOrBird;
    localStorage.setItem('username', randomName);
    return randomName;
};

export default getRandomName;